"""Added table that connects users and boards

Revision ID: 07342ab9c6e5
Revises: fc517dbbb15c
Create Date: 2022-05-25 13:12:23.358014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07342ab9c6e5'
down_revision = 'fc517dbbb15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_boards',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name=op.f('fk__users_boards__board_id__board')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__users_boards__user_id__users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_boards')
    # ### end Alembic commands ###
