"""Fixed ration on deleted tasks

Revision ID: 36744eb512b9
Revises: f2272a9ff5f0
Create Date: 2022-05-13 02:19:51.292945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36744eb512b9'
down_revision = 'f2272a9ff5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_deletedtasks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['delete.task_id'], name=op.f('fk__users_deletedtasks__task_id__delete')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__users_deletedtasks__user_id__users'))
    )
    op.drop_constraint('fk__users_tasks__delete_id__delete', 'users_tasks', type_='foreignkey')
    op.drop_column('users_tasks', 'delete_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('delete_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk__users_tasks__delete_id__delete', 'users_tasks', 'delete', ['delete_id'], ['task_id'])
    op.drop_table('users_deletedtasks')
    # ### end Alembic commands ###
