"""Add roles to board users

Revision ID: 382d424ec59f
Revises: 434aaf8c7cb3
Create Date: 2022-07-13 15:29:43.717776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382d424ec59f'
down_revision = '434aaf8c7cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('uq__users__name'), 'users', ['name'])
    op.add_column('users_boards', sa.Column('user_position', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_boards', 'user_position')
    op.drop_constraint(op.f('uq__users__name'), 'users', type_='unique')
    op.alter_column('tasks', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
