"""Fixed deleted task table

Revision ID: 426fc79fb0ff
Revises: 87122c5e212a
Create Date: 2022-07-18 06:29:33.901417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426fc79fb0ff'
down_revision = '87122c5e212a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__comments__board_id__board'), 'comments', 'board', ['board_id'], ['board_id'])
    op.add_column('delete', sa.Column('name', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False))
    op.add_column('delete', sa.Column('description', sa.String(collation='ru-RU-x-icu'), nullable=True))
    op.add_column('delete', sa.Column('stage', sa.Integer(), nullable=True))
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('delete', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('delete', 'attachments')
    op.drop_column('delete', 'comments')
    op.drop_column('delete', 'completed')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.add_column('delete', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('delete', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('delete', sa.Column('attachments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('delete', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('delete', 'stage')
    op.drop_column('delete', 'description')
    op.drop_column('delete', 'name')
    op.drop_constraint(op.f('fk__comments__board_id__board'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'board_id')
    # ### end Alembic commands ###
