"""Fixings

Revision ID: 434aaf8c7cb3
Revises: fb3e2ec14eb5
Create Date: 2022-05-26 15:47:15.350354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434aaf8c7cb3'
down_revision = 'fb3e2ec14eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
