"""Initial

Revision ID: 453159ba9cbc
Revises: 
Create Date: 2022-05-13 02:10:50.401453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453159ba9cbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(collation='ru-RU-x-icu'), nullable=True),
    sa.PrimaryKeyConstraint('board_id', name=op.f('pk__board'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(collation='ru-RU-x-icu'), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('yandex_email', sa.String(length=256), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq__users__telegram_id')),
    sa.UniqueConstraint('yandex_email', name=op.f('uq__users__yandex_email'))
    )
    op.create_table('delete',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(collation='ru-RU-x-icu'), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name=op.f('fk__delete__board_id__board')),
    sa.UniqueConstraint('task_id', name=op.f('uq__delete__task_id'))
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(collation='ru-RU-x-icu'), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(collation='ru-RU-x-icu'), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name=op.f('fk__tasks__board_id__board')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk__tasks'))
    )
    op.create_table('users_tasks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk__users_tasks__task_id__tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk__users_tasks__user_id__users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tasks')
    op.drop_table('tasks')
    op.drop_table('delete')
    op.drop_table('users')
    op.drop_table('board')
    # ### end Alembic commands ###
