"""Changes default value of stage from False to 0

Revision ID: 4afcfe10d384
Revises: 8f9ca4dc71f9
Create Date: 2022-07-21 03:59:42.851800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afcfe10d384'
down_revision = '8f9ca4dc71f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
