"""Added author to files

Revision ID: 87122c5e212a
Revises: b0ac013d6a9c
Create Date: 2022-07-15 01:36:13.343336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87122c5e212a'
down_revision = 'b0ac013d6a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__files__author_id__users'), 'files', 'users', ['author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__files__author_id__users'), 'files', type_='foreignkey')
    op.drop_column('files', 'author_id')
    # ### end Alembic commands ###
