"""Fixed deleted task table

Revision ID: 8f9ca4dc71f9
Revises: 17702ddd1543
Create Date: 2022-07-18 06:42:33.844920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9ca4dc71f9'
down_revision = '17702ddd1543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
