"""Added author of the comments

Revision ID: b0ac013d6a9c
Revises: c8ba6f16dd27
Create Date: 2022-07-14 21:43:11.739845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ac013d6a9c'
down_revision = 'c8ba6f16dd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__users__yandex_email', 'users', type_='unique')
    op.drop_column('users', 'yandex_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_email', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq__users__yandex_email', 'users', ['yandex_email'])
    # ### end Alembic commands ###
