"""Added authors to tasks

Revision ID: c20ba078bcc2
Revises: df45a0e4ebf5
Create Date: 2022-08-04 04:29:46.420627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20ba078bcc2'
down_revision = 'df45a0e4ebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delete', sa.Column('author_id', sa.Integer(), nullable=True))
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_foreign_key(op.f('fk__delete__author_id__users'), 'delete', 'users', ['author_id'], ['user_id'])
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__tasks__author_id__users'), 'tasks', 'users', ['author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__tasks__author_id__users'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'author_id')
    op.drop_constraint(op.f('fk__delete__author_id__users'), 'delete', type_='foreignkey')
    op.alter_column('delete', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('delete', 'author_id')
    # ### end Alembic commands ###
