"""Added author of the comments

Revision ID: c8ba6f16dd27
Revises: fd61957c9fc8
Create Date: 2022-07-14 20:49:35.798356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ba6f16dd27'
down_revision = 'fd61957c9fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__comments__author_id__users'), 'comments', 'users', ['author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__comments__author_id__users'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
