"""Fixing last upgrade

Revision ID: dee10b361038
Revises: 08050c5964e5
Create Date: 2022-05-26 13:49:51.245524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee10b361038'
down_revision = '08050c5964e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('content', sa.String(length=5000), nullable=False))
    op.create_foreign_key(op.f('fk__comments__task_id__tasks'), 'comments', 'tasks', ['task_id'], ['task_id'])
    op.add_column('files', sa.Column('filename', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'filename')
    op.drop_constraint(op.f('fk__comments__task_id__tasks'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'content')
    op.drop_column('comments', 'task_id')
    # ### end Alembic commands ###
