"""Added names to names (like name -> username)

Revision ID: df45a0e4ebf5
Revises: 4afcfe10d384
Create Date: 2022-08-02 01:29:55.996150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df45a0e4ebf5'
down_revision = '4afcfe10d384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('boardname', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False))
    op.drop_column('board', 'name')
    op.add_column('delete', sa.Column('taskname', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False))
    op.drop_column('delete', 'name')
    op.add_column('tasks', sa.Column('taskname', sa.String(length=64, collation='ru-RU-x-icu'), nullable=False))
    op.drop_column('tasks', 'name')
    op.add_column('users', sa.Column('username', sa.String(collation='ru-RU-x-icu'), nullable=True))
    op.drop_constraint('uq__users__name', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq__users__username'), 'users', ['username'])
    op.drop_column('users', 'name')
    op.alter_column('users_boards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_boards', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_tasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_tasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_boards', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_boards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq__users__username'), 'users', type_='unique')
    op.create_unique_constraint('uq__users__name', 'users', ['name'])
    op.drop_column('users', 'username')
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'taskname')
    op.add_column('delete', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('delete', 'taskname')
    op.add_column('board', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('board', 'boardname')
    # ### end Alembic commands ###
