"""Added ration to deleted tasks

Revision ID: f2272a9ff5f0
Revises: 453159ba9cbc
Create Date: 2022-05-13 02:16:03.031526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2272a9ff5f0'
down_revision = '453159ba9cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('delete_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__users_tasks__delete_id__delete'), 'users_tasks', 'delete', ['delete_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__users_tasks__delete_id__delete'), 'users_tasks', type_='foreignkey')
    op.drop_column('users_tasks', 'delete_id')
    # ### end Alembic commands ###
