"""Add date_time column in comments table

Revision ID: f2624d0fc6e1
Revises: 382d424ec59f
Create Date: 2022-07-13 16:55:24.014200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2624d0fc6e1'
down_revision = '382d424ec59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_time')
    # ### end Alembic commands ###
