"""Fixings

Revision ID: fb3e2ec14eb5
Revises: dee10b361038
Create Date: 2022-05-26 14:37:21.291842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3e2ec14eb5'
down_revision = 'dee10b361038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'comments')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_unique_constraint(op.f('uq__users__phone_number'), 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__phone_number'), 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('tasks', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
