"""Test

Revision ID: fc517dbbb15c
Revises: a14ab721edee
Create Date: 2022-05-13 03:14:56.661310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc517dbbb15c'
down_revision = 'a14ab721edee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
