"""Changed task <completed> to <stage>

Revision ID: fd61957c9fc8
Revises: f2624d0fc6e1
Create Date: 2022-07-14 16:50:54.899186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd61957c9fc8'
down_revision = 'f2624d0fc6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('stage', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'stage')
    # ### end Alembic commands ###
